#! /bin/bash
#mvn clean install -D skipTests
onos-app 127.0.0.1 uninstall org.netarch.odb.compiler
onos-app 127.0.0.1 install /home/$USER/odb/compiler/target/compiler-1.0-SNAPSHOT.oar
onos-app 127.0.0.1 activate org.netarch.odb.compiler
